assert_lefthook_installed: true
output: [execution, failure, summary]
pre-commit:
  commands:
    format:
      run: dprint fmt
      stage_fixed: true
pre-push:
  commands:
    lint:
      run: cargo clippy --all-targets --all-features --workspace
