name: docs
on:
  push:
    branches: [main]
    paths: ['src/**/*.rs', 'Cargo.toml', '.github/workflows/docs.yml']
  workflow_dispatch:

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2.7.3

      - name: Build docs
        run: make build.docs

      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./target/doc
      - uses: actions/deploy-pages@v4
        id: deploy
